# Generated by Django 5.2.4 on 2025-07-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingtask",
            name="generated_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_tasks",
                to="music_processing.generatedtrack",
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_tasks",
                to="music_processing.song",
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="stem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_tasks",
                to="music_processing.stem",
            ),
        ),
    ]
