# Generated by Django 5.2.4 on 2025-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_processing", "0002_alter_processingtask_generated_track_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedtrack",
            name="gen_outro",
            field=models.CharField(
                choices=[
                    ("Auto", "Automático"),
                    ("Force", "Forzar"),
                    ("Disable", "Desactivar"),
                ],
                default="Auto",
                max_length=20,
            ),
        ),
    ]
