# Generated by Django 4.2.23 on 2025-08-04 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("music_processing", "0003_alter_generatedtrack_gen_outro"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_tracks/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_versions",
                        to="music_processing.generatedtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["version_number"],
                "unique_together": {("track", "version_number")},
            },
        ),
    ]
