# Generated by Django 4.2.23 on 2025-08-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_processing", "0004_generatedversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedtrack",
            name="add_drums",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="generatedtrack",
            name="add_outro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="generatedtrack",
            name="apply_sustains",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="generatedtrack",
            name="model_top_p",
            field=models.FloatField(default=0.96),
        ),
        migrations.AddField(
            model_name="generatedtrack",
            name="prime_instruments_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="generatedtrack",
            name="remove_duplicate_pitches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="generatedtrack",
            name="remove_overlapping_durations",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="generatedtrack",
            name="gen_outro",
            field=models.CharField(default="Auto", max_length=20),
        ),
        migrations.AlterField(
            model_name="generatedtrack",
            name="num_gen_tokens",
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name="generatedtrack",
            name="num_prime_tokens",
            field=models.IntegerField(default=6656),
        ),
    ]
